name: Build injector (Android aarch64)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NDK_VERSION: "android-ndk-r25b"
  NDK_ZIP: "android-ndk-r25b-linux.zip"
  API_LEVEL: "21"
  SRC: "injector_arm64.c"
  OUT_BIN: "injector_arm64"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup tools
        run: sudo apt-get update && sudo apt-get install -y curl unzip

      - name: Download Android NDK zip
        run: |
          curl -L -o "${NDK_ZIP}" "https://dl.google.com/android/repository/${NDK_ZIP}"

      - name: Unpack NDK
        run: |
          unzip -q "${NDK_ZIP}" -d ./ndk
          NDK_DIR=$(find ./ndk -maxdepth 1 -type d -name "${NDK_VERSION}*" | head -n1)
          echo "NDK_DIR=$NDK_DIR" >> $GITHUB_ENV

      - name: Build injector (aarch64)
        run: |
          set -euo pipefail
          CLANG="$NDK_DIR/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android${API_LEVEL}-clang"
          $CLANG -O2 -fPIE -pie -o "${OUT_BIN}" "${SRC}" -ldl
          file ${OUT_BIN}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: injector-aarch64
          path: injector_arm64
