name: Build libmain.so

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download NDK r28c
      run: |
        wget -O android-ndk-r28c-linux.zip https://dl.google.com/android/repository/android-ndk-r28c-linux.zip
        unzip -q android-ndk-r28c-linux.zip
        echo "ANDROID_NDK=$PWD/android-ndk-r28c" >> $GITHUB_ENV
        echo "$PWD/android-ndk-r28c/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

    - name: Build libmain.so (arm64-v8a)
      run: |
        mkdir -p out_libs/arm64-v8a
        aarch64-linux-android21-clang++ -fPIC -shared wrapper.cpp \
          -o out_libs/arm64-v8a/libmain.so -llog -ldl

    - name: Build libmain.so (armeabi-v7a)
      run: |
        mkdir -p out_libs/armeabi-v7a
        armv7a-linux-androideabi21-clang++ -fPIC -shared wrapper.cpp \
          -o out_libs/armeabi-v7a/libmain.so -llog -ldl

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libmain-builds
        path: out_libs/
