name: Android NDK Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: "r26b"
      ANDROID_API_LEVEL: 30
      ANDROID_ABI: arm64-v8a

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=${{ env.ANDROID_ABI }} \
            -DANDROID_PLATFORM=android-${{ env.ANDROID_API_LEVEL }}

      - name: Build
        run: cmake --build build

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: overlaydemo_hwclayer-${{ env.ANDROID_ABI }}
          path: build/overlaydemo_hwclayer
